# node js official image
FROM node:18-alpine

# create a directory for the application
WORKDIR /app

# copy package.json and package-lock.json
COPY package*.json ./

# install the dependencies
RUN npm install

# copy all the project files
COPY . .

RUN mkdir -p uploads && chmod 777 uploads

# expose the port on which the application will run
EXPOSE your_port_app

# Command to start the application
CMD ["npm", "start"]
